name: 'Build'

on:
  pull_request: {}

jobs:
  check:
    uses: zenhelix/ci-workflows/.github/workflows/app-check.yml@v4
    with:
      java-version: '17'

  label:
    uses: zenhelix/ci-workflows/.github/workflows/labeler.yml@v4
